package game

import "slices"

// WorldOptions are creation-time configuration. Terrain and all consequences
// are generated by Go and checkpointed; clients never submit map tiles.
type WorldOptions struct {
	Type          string `json:"type,omitempty"`
	Biome         string `json:"biome,omitempty"`
	Size          string `json:"size,omitempty"`
	Resources     string `json:"resources,omitempty"`
	Separation    string `json:"separation,omitempty"`
	Reveal        string `json:"reveal,omitempty"`
	TreatyMinutes int    `json:"treaty_minutes,omitempty"`
}

type WorldChoice struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type WorldSize struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Tiles       int    `json:"tiles"`
}

type WorldCatalog struct {
	Types         []WorldChoice `json:"types"`
	Biomes        []WorldChoice `json:"biomes"`
	Sizes         []WorldSize   `json:"sizes"`
	Resources     []WorldChoice `json:"resources"`
	Separations   []WorldChoice `json:"separations"`
	Reveals       []WorldChoice `json:"reveals"`
	TreatyMinutes []int         `json:"treaty_minutes"`
	Defaults      WorldOptions  `json:"defaults"`
}

func worldCatalog() WorldCatalog {
	return WorldCatalog{
		Types: []WorldChoice{
			{"plains", "Open Plains", "Open country with scattered woods and room to expand in every direction."},
			{"forest", "Forest Marches", "Wooded regions surround clearings. Shared paths and tree cutting open routes between kingdoms."},
			{"highlands", "Highland Relics", "Walkable hills and plateaus rise beside steep ridges, with passes leading to the central relics."},
			{"rivers", "River Kingdoms", "A winding river, shared fishing, and shallow crossings connect the settlements."},
			{"lakes", "Twin Seas", "Two inland lakes support fishing while land routes remain open around their shores."},
			{"coast", "Coastal Frontier", "A shared mainland meets a broad sea, with room for land and naval economies."},
			{"islands", "Island Crowns", "Separate home islands and a neutral island. Fishing ships explore the sea; transports carry units to new shores."},
			{"protected", "Walled Basin", "Each kingdom begins inside a palisade with gates, with further resources beyond its walls."},
		},
		Biomes: []WorldChoice{
			{"temperate", "Temperate", "Green meadows, mixed woodland, and cool blue water."},
			{"desert", "Desert", "Warm sand, dry earth, and palms along turquoise shores."},
			{"alpine", "Alpine", "Snowy ground, dark evergreens, and slate-blue water."},
			{"tropical", "Tropical", "Lush green ground, broad canopies, and bright coastal water."},
		},
		Sizes: []WorldSize{
			{"small", "Small", "A compact world with shorter journeys.", 96},
			{"medium", "Medium", "Room for exploration and several expanding settlements.", 128},
			{"large", "Large", "Longer journeys and more space between regions.", 160},
		},
		Resources: []WorldChoice{
			{"scarce", "Scarce", "Natural deposits hold 70% of the standard amount. Starting stockpiles stay the same."},
			{"standard", "Standard", "The standard amount of food, wood, gold, and stone in natural deposits."},
			{"abundant", "Abundant", "Natural deposits hold 175% of the standard amount. Starting stockpiles stay the same."},
		},
		Separations: []WorldChoice{
			{"close", "Close", "Settlements start nearer the center, with a minimum clearance for every home economy."},
			{"standard", "Standard", "Settlements share a broad ring around the central countryside."},
			{"far", "Far apart", "Settlements start closer to the outer reaches of the map."},
		},
		Reveals: []WorldChoice{
			{"hidden", "Unexplored", "Explore to uncover terrain, resources, and other settlements."},
			{"explored", "Terrain revealed", "See the terrain from the start. Units and resources still require scouting."},
			{"all", "Everything visible", "All kingdoms share full map visibility throughout the game."},
		},
		TreatyMinutes: []int{0, 5, 10, 20, 30},
		Defaults:      WorldOptions{Type: "rivers", Biome: "temperate", Size: "small", Resources: "standard", Separation: "standard", Reveal: "hidden"},
	}
}

func normalizeWorldOptions(options WorldOptions) (WorldOptions, error) {
	catalog := worldCatalog()
	fields := []struct {
		value                *string
		fallback, code, name string
		choices              []WorldChoice
	}{
		{&options.Type, catalog.Defaults.Type, "invalid_world_type", "world type", catalog.Types},
		{&options.Biome, catalog.Defaults.Biome, "invalid_biome", "biome", catalog.Biomes},
		{&options.Resources, catalog.Defaults.Resources, "invalid_resource_abundance", "resource abundance", catalog.Resources},
		{&options.Separation, catalog.Defaults.Separation, "invalid_starting_separation", "starting separation", catalog.Separations},
		{&options.Reveal, catalog.Defaults.Reveal, "invalid_map_reveal", "map reveal", catalog.Reveals},
	}
	for _, field := range fields {
		if *field.value == "" {
			*field.value = field.fallback
		}
		if !slices.ContainsFunc(field.choices, func(choice WorldChoice) bool { return choice.ID == *field.value }) {
			return options, rule(field.code, "Choose a "+field.name+" from the world catalog.")
		}
	}
	if options.Size == "" {
		options.Size = catalog.Defaults.Size
	}
	if !slices.ContainsFunc(catalog.Sizes, func(size WorldSize) bool { return size.ID == options.Size }) {
		return options, rule("invalid_world_size", "Choose a world size from the catalog.")
	}
	if !slices.Contains(catalog.TreatyMinutes, options.TreatyMinutes) {
		return options, rule("invalid_peace_period", "Choose a peace period of 0, 5, 10, 20, or 30 game minutes.")
	}
	return options, nil
}

func worldSize(options WorldOptions) int {
	for _, size := range worldCatalog().Sizes {
		if size.ID == options.Size {
			return size.Tiles
		}
	}
	return 96
}

func (w *World) WorldOptions() WorldOptions {
	if w.Generation == 0 {
		return WorldOptions{Biome: "temperate"}
	}
	if w.Config.World.Type != "" {
		return w.Config.World
	}
	options, _ := normalizeWorldOptions(w.Config.World)
	return options
}

func (w *World) resourceMultiplier() float64 {
	switch w.Config.World.Resources {
	case "scarce":
		return .7
	case "abundant":
		return 1.75
	default:
		return 1
	}
}
