// Code generated by go run ./cmd/contracts. DO NOT EDIT.

export interface Action {
  kind: string;
  product?: string;
  label: string;
  description: string;
  cost: Resources;
  gain?: Resources;
  duration: number;
  enabled: boolean;
  reason?: string;
}

export interface Catalog {
  rules_version: string;
  definitions: Definition[];
  technologies: Technology[];
  civilizations: Civilization[];
  ages: string[];
  speeds: number[];
  difficulties: Difficulty[];
  log_filters: LogFilter[];
  settlement_counts: number[];
  worlds: WorldCatalog;
}

export interface Civilization {
  id: string;
  name: string;
  description: string;
  bonus: string;
}

export interface Command {
  id: string;
  kind: string;
  entity_ids?: number[];
  target_id?: number;
  target_player?: number;
  position?: Vec;
  product?: string;
  queue?: boolean;
  value?: number;
}

export interface Config {
  name?: string;
  settlements?: number;
  seed: number;
  civilization: string;
  difficulty: string;
  mode: string;
  world?: WorldOptions;
}

export interface Definition {
  id: string;
  name: string;
  kind: string;
  description: string;
  cost: Resources;
  age: number;
  time: number;
  hp: number;
  radius: number;
  speed: number;
  attack: number;
  armor: number;
  pierce_armor: number;
  range: number;
  min_range: number;
  reload: number;
  sight: number;
  population: number;
  housing: number;
  producer?: string;
  prerequisite?: string;
  class?: string;
  drop_off?: string[];
  naval: boolean;
  projectile: boolean;
}

export interface Difficulty {
  id: string;
  name: string;
  description: string;
}

export interface EntityView {
  id: number;
  type: string;
  kind: string;
  name: string;
  owner: number;
  position: Vec;
  hp: number;
  max_hp: number;
  radius: number;
  progress: number;
  amount?: number;
  resource?: string;
  cargo?: number;
  cargo_type?: string;
  state: string;
  stance?: string;
  activity: string;
  visible: boolean;
  actions: Action[];
  tasks: Task[];
  rally?: Vec;
  deployed: boolean;
  passengers: number[];
  container?: number;
  relic: boolean;
  faith?: number;
}

export interface ErrorBody {
  error: RuleError;
}

export interface Event {
  id: number;
  tick: number;
  time: number;
  message: string;
  kind: string;
  entity_id?: number;
  entity_name?: string;
  entity_type?: string;
  state?: string;
  previous_state?: string;
  lifecycle?: string;
  command_id?: string;
  target_id?: number;
  activity?: string;
  resource?: string;
  amount?: number;
  position: Vec;
}

export interface EventPage {
  events: Event[];
  older_cursor: number;
  newer_cursor: number;
  latest_cursor: number;
  has_older: boolean;
  has_newer: boolean;
  entity?: HistoryEntity;
}

export interface Health {
  status: string;
  rules_version: string;
}

export interface HistoryEntity {
  id: number;
  name: string;
  type: string;
  activity: string;
  present: boolean;
}

export interface LogFilter {
  id: string;
  name: string;
}

export interface MapView {
  width: number;
  height: number;
  biome: string;
  tiles: Tile[];
  fog: number[];
}

export interface OpponentView {
  id: number;
  name: string;
  civilization: string;
  defeated: boolean;
  relation: string;
  temperament: string;
}

export interface Placement {
  product: string;
  position: Vec;
}

export interface PlacementResult {
  valid: boolean;
  reason?: string;
}

export interface PlayerView {
  id: number;
  name: string;
  civilization: string;
  resources: Resources;
  age: number;
  age_name: string;
  population: number;
  capacity: number;
  limit: number;
  idle: number;
  workers: number;
  military: number;
  technologies: string[];
  defeated: boolean;
  kills: number;
}

export interface ProjectileView {
  id: number;
  owner: number;
  position: Vec;
  kind: string;
}

export interface Receipt {
  command_id: string;
  tick: number;
  accepted: boolean;
}

export interface Resources {
  food: number;
  wood: number;
  gold: number;
  stone: number;
}

export interface ResumeRequest {
  identifier: string;
}

export interface RuleError {
  code: string;
  message: string;
}

export interface SavedGame {
  world: WorldOptions;
  match_id: string;
  name: string;
  saved_at: string;
  time: number;
  difficulty: string;
  settlements: number;
  status: string;
  active: boolean;
  autosave_seconds: number;
  save_error?: string;
}

export interface SavedGames {
  games: SavedGame[];
}

export interface Session {
  match_id: string;
  token: string;
  player_id: number;
  name: string;
}

export interface Snapshot {
  version: string;
  difficulty: Difficulty;
  settlements: number;
  world: WorldOptions;
  treaty_remaining: number;
  tick: number;
  time: number;
  speed: number;
  paused: boolean;
  status: string;
  winner: number;
  player: PlayerView;
  opponents: OpponentView[];
  map: MapView;
  entities: EntityView[];
  projectiles: ProjectileView[];
  events: Event[];
  event_cursor: number;
  build_options: Action[];
}

export interface Task {
  type: string;
  product: string;
  remaining: number;
  duration: number;
  paid: Resources;
}

export interface Technology {
  id: string;
  name: string;
  description: string;
  producer: string;
  age: number;
  cost: Resources;
  time: number;
  prerequisite?: string;
}

export interface Tile {
  terrain: string;
  elevation: number;
}

export interface Vec {
  x: number;
  y: number;
}

export interface WorldCatalog {
  types: WorldChoice[];
  biomes: WorldChoice[];
  sizes: WorldSize[];
  resources: WorldChoice[];
  separations: WorldChoice[];
  reveals: WorldChoice[];
  treaty_minutes: number[];
  defaults: WorldOptions;
}

export interface WorldChoice {
  id: string;
  name: string;
  description: string;
}

export interface WorldOptions {
  type?: string;
  biome?: string;
  size?: string;
  resources?: string;
  separation?: string;
  reveal?: string;
  treaty_minutes?: number;
}

export interface WorldSize {
  id: string;
  name: string;
  description: string;
  tiles: number;
}

