// Code generated by go run ./cmd/contracts. DO NOT EDIT.

export interface Action {
  kind: string;
  product?: string;
  label: string;
  description: string;
  cost: Resources;
  gain?: Resources;
  duration: number;
  enabled: boolean;
  reason?: string;
}

export interface AgentConnectionRequest {
  connection_id: string;
}

export interface AgentConnectionResult {
  ok: boolean;
}

export interface AgentEndpoint {
  game_id: string;
  membership_id: string;
  player_id: number;
  mcp_url: string;
  token?: string;
}

export interface AgentGame {
  game_id: string;
  name: string;
  player_id: number;
  seat_id: string;
  owner: boolean;
  status: string;
  match_status: string;
  revision: number;
  time: number;
}

export interface AgentLogRequest {
  after?: number;
  before?: number;
  limit?: number;
  entity_id?: number;
  q?: string;
  category?: string;
}

export interface ArchivePassword {
  passphrase: string;
}

export interface AuditEvent {
  audience: string;
  actor_name: string;
  id: number;
  at: string;
  actor: string;
  action: string;
  message: string;
}

export interface AuditPage {
  events: AuditEvent[];
}

export interface BiomeEconomy {
  biome: string;
  deposits: Resources;
  description: string;
}

export interface Catalog {
  commands: CommandInfo[];
  rules_version: string;
  definitions: Definition[];
  technologies: Technology[];
  civilizations: Civilization[];
  ages: string[];
  speeds: number[];
  difficulties: Difficulty[];
  log_filters: LogFilter[];
  settlement_counts: number[];
  worlds: WorldCatalog;
}

export interface Civilization {
  id: string;
  name: string;
  description: string;
  bonus: string;
}

export interface ClaimInvite {
  id: string;
  secret: string;
  name: string;
}

export interface Command {
  trade_mode?: string;
  trade_limit?: number;
  offer?: TradeOfferIntent;
  offer_id?: number;
  shipment_id?: number;
  repeat?: boolean;
  market_revision?: number;
  end_position?: Vec;
  id: string;
  kind: string;
  entity_ids?: number[];
  target_id?: number;
  target_player?: number;
  position?: Vec;
  product?: string;
  queue?: boolean;
  value?: number;
}

export interface CommandInfo {
  kind: string;
  description: string;
  fields: string[];
}

export interface CompleteTransfer {
  id: string;
  revision: number;
  receipt: string;
}

export interface Config {
  name?: string;
  settlements?: number;
  seed: number;
  civilization: string;
  difficulty: string;
  mode: string;
  world?: WorldOptions;
}

export interface ConnectionInfo {
  id: string;
  epoch: string;
}

export interface CreateGame {
  config: Config;
  friends: number;
  player_name: string;
}

export interface Definition {
  id: string;
  name: string;
  kind: string;
  description: string;
  cost: Resources;
  age: number;
  time: number;
  hp: number;
  radius: number;
  speed: number;
  attack: number;
  armor: number;
  pierce_armor: number;
  range: number;
  min_range: number;
  reload: number;
  sight: number;
  population: number;
  housing: number;
  producer?: string;
  prerequisite?: string;
  class?: string;
  drop_off?: string[];
  naval: boolean;
  projectile: boolean;
}

export interface Difficulty {
  id: string;
  name: string;
  description: string;
}

export interface EntityView {
  connections?: Vec[];
  appearance_age?: number;
  id: number;
  type: string;
  kind: string;
  name: string;
  owner: number;
  position: Vec;
  hp: number;
  max_hp: number;
  radius: number;
  progress: number;
  amount?: number;
  resource?: string;
  cargo?: number;
  cargo_type?: string;
  state: string;
  stance?: string;
  activity: string;
  visible: boolean;
  actions: Action[];
  tasks: Task[];
  rally?: Vec;
  deployed: boolean;
  passengers: number[];
  container?: number;
  relic: boolean;
  faith?: number;
}

export interface ErrorBody {
  error: RuleError;
}

export interface Event {
  user_id: string;
  id: number;
  tick: number;
  time: number;
  message: string;
  player_id: number;
  kind: string;
  entity_id?: number;
  entity_name?: string;
  entity_type?: string;
  state?: string;
  previous_state?: string;
  lifecycle?: string;
  command_id?: string;
  target_id?: number;
  activity?: string;
  resource?: string;
  amount?: number;
  position: Vec;
}

export interface EventPage {
  events: Event[];
  older_cursor: number;
  newer_cursor: number;
  latest_cursor: number;
  has_older: boolean;
  has_newer: boolean;
  entity?: HistoryEntity;
}

export interface GameControl {
  id: string;
  revision: number;
  value?: number;
  confirm?: boolean;
}

export interface GameInfo {
  game_id: string;
  name: string;
  config: Config;
  status: string;
  match_status: string;
  runtime: string;
  epoch: string;
  revision: number;
  seats: SeatView[];
  owner: boolean;
  player_id: number;
  time: number;
  saved_at: string;
  save_error?: string;
  can_start: boolean;
  start_reason: string;
  transfer_id?: string;
}

export interface GameLibrary {
  games: GameInfo[];
}

export interface Health {
  status: string;
  rules_version: string;
}

export interface HistoryEntity {
  id: number;
  name: string;
  type: string;
  activity: string;
  present: boolean;
}

export interface ImportResult {
  session: MemberSession;
  completion_receipt?: string;
  already_imported: boolean;
}

export interface Invitation {
  id: string;
  game_id: string;
  game_name: string;
  seat_id: string;
  name: string;
  expires_at: string;
  secret?: string;
}

export interface InviteRequest {
  id: string;
  revision: number;
  replace: boolean;
}

export interface InviteSecret {
  secret: string;
}

export interface LogFilter {
  id: string;
  name: string;
}

export interface MapCell {
  index: number;
  tile: Tile;
  fog: number;
}

export interface MapRegion {
  tick: number;
  map_width: number;
  map_height: number;
  x: number;
  y: number;
  width: number;
  height: number;
  tiles: Tile[];
  fog: number[];
}

export interface MapRegionRequest {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface MapView {
  width: number;
  height: number;
  biome: string;
  tiles: Tile[];
  fog: number[];
}

export interface MarketplaceView {
  markets: RegionalMarketView[];
  offers: TradeOfferView[];
  shipments: TradeShipmentView[];
  merchants: MerchantView;
  reserved: Resources;
  capacity: number;
  max_lots: number;
  max_offers: number;
}

export interface MemberSession {
  match_id: string;
  token: string;
  player_id: number;
  name: string;
  membership_id: string;
  rejoin_code?: string;
  epoch: string;
  owner: boolean;
}

export interface MerchantRouteView {
  product: string;
  mode: string;
  cost: Resources;
  gain: Resources;
  can_start: boolean;
  reason?: string;
  cart_id?: number;
  home_margin: number;
}

export interface MerchantView {
  region_id: number;
  biome: string;
  production: Resources;
  demand: Resources;
  supply_state: string;
  supply_interval: number;
  next_supply_in: number;
  supply_cart_id?: number;
  supply_position?: Vec;
  stock: Resources;
  revision: number;
  market_id?: number;
  actions: Action[];
}

export interface Observation {
  snapshot: Snapshot;
  map_included: boolean;
  has_more: boolean;
  next_entity_id: number;
}

export interface ObserveRequest {
  owner?: number;
  entity_ids?: number[];
  after_entity_id?: number;
  limit?: number;
  include_map?: boolean;
}

export interface OpponentView {
  id: number;
  name: string;
  civilization: string;
  defeated: boolean;
  relation: string;
  temperament: string;
}

export interface Placement {
  end_position?: Vec;
  product: string;
  position: Vec;
}

export interface PlacementResult {
  positions: Vec[];
  cost: Resources;
  valid: boolean;
  reason?: string;
}

export interface PlayerView {
  id: number;
  name: string;
  civilization: string;
  resources: Resources;
  production: ProductionView;
  age: number;
  age_name: string;
  population: number;
  capacity: number;
  limit: number;
  idle: number;
  workers: number;
  military: number;
  technologies: string[];
  defeated: boolean;
  kills: number;
}

export interface ProductionSample {
  time: number;
  rates: Resources;
}

export interface ProductionView {
  rates: Resources;
  history: ProductionSample[];
  window_seconds: number;
  sample_seconds: number;
}

export interface ProjectileView {
  id: number;
  owner: number;
  position: Vec;
  kind: string;
}

export interface ReadyRequest {
  id: string;
  revision: number;
  ready: boolean;
}

export interface Receipt {
  command_id: string;
  tick: number;
  accepted: boolean;
}

export interface RegionalMarketView {
  merchant: MerchantView;
  position: Vec;
  routes: MerchantRouteView[];
}

export interface RejoinRequest {
  code: string;
}

export interface Resources {
  food: number;
  wood: number;
  gold: number;
  stone: number;
}

export interface ResumeRequest {
  identifier: string;
}

export interface RuleError {
  code: string;
  message: string;
}

export interface RulesChange {
  id: string;
  revision: number;
  config: Config;
}

export interface SavedGame {
  world: WorldOptions;
  match_id: string;
  name: string;
  saved_at: string;
  time: number;
  difficulty: string;
  settlements: number;
  status: string;
  active: boolean;
  autosave_seconds: number;
  save_error?: string;
}

export interface SavedGames {
  games: SavedGame[];
}

export interface SeatChange {
  id: string;
  revision: number;
  name: string;
  civilization: string;
  controller: string;
}

export interface SeatView {
  id: string;
  player_id: number;
  membership_id?: string;
  name: string;
  civilization: string;
  controller: string;
  status: string;
  ready: boolean;
  connected: boolean;
  owner: boolean;
  yours: boolean;
  invite_id?: string;
  invite_expires_at?: string;
}

export interface Session {
  match_id: string;
  token: string;
  player_id: number;
  name: string;
}

export interface Snapshot {
  marketplace: MarketplaceView;
  control_revision?: number;
  version: string;
  difficulty: Difficulty;
  settlements: number;
  world: WorldOptions;
  treaty_remaining: number;
  tick: number;
  time: number;
  speed: number;
  paused: boolean;
  status: string;
  winner: number;
  player: PlayerView;
  opponents: OpponentView[];
  map: MapView;
  entities: EntityView[];
  projectiles: ProjectileView[];
  events: Event[];
  event_cursor: number;
  build_options: Action[];
}

export interface SnapshotDelta {
  marketplace?: MarketplaceView;
  control_revision: number;
  tick: number;
  time: number;
  speed: number;
  paused: boolean;
  status: string;
  winner: number;
  treaty_remaining: number;
  player?: PlayerView;
  opponents?: OpponentView[];
  cells?: MapCell[];
  entities?: EntityView[];
  removed_entities?: number[];
  projectiles: ProjectileView[];
  events?: Event[];
  event_cursor: number;
  build_options?: Action[];
}

export interface SnapshotFrame {
  sequence: number;
  base: number;
  sample_ms: number;
  snapshot?: Snapshot;
  delta?: SnapshotDelta;
}

export interface Task {
  type: string;
  product: string;
  remaining: number;
  duration: number;
  paid: Resources;
}

export interface Technology {
  id: string;
  name: string;
  description: string;
  producer: string;
  age: number;
  cost: Resources;
  time: number;
  prerequisite?: string;
}

export interface Tile {
  biome?: string;
  terrain: string;
  elevation: number;
}

export interface TradeOfferIntent {
  give_resource: string;
  give_amount: number;
  want_resource: string;
  want_amount: number;
  lots: number;
  target_player?: number;
}

export interface TradeOfferView {
  id: number;
  owner: number;
  terms: TradeOfferIntent;
  remaining: number;
  state: string;
  market_id?: number;
  position?: Vec;
  can_accept: boolean;
  reason?: string;
  cart_id?: number;
}

export interface TradeShipmentView {
  merchant_id?: number;
  trade_mode?: string;
  price_limit?: number;
  id: number;
  offer_id: number;
  seller: number;
  buyer: number;
  terms: TradeOfferIntent;
  state: string;
  status: string;
  cart_id?: number;
  position?: Vec;
  can_resume: boolean;
  can_recall: boolean;
  repeat: boolean;
}

export interface TransferInfo {
  id: string;
  game_id: string;
  kind: string;
  status: string;
  download_path: string;
}

export interface TransferRequest {
  id: string;
  revision: number;
  kind: string;
}

export interface Vec {
  x: number;
  y: number;
}

export interface WorldCatalog {
  economies: BiomeEconomy[];
  types: WorldChoice[];
  biomes: WorldChoice[];
  sizes: WorldSize[];
  resources: WorldChoice[];
  separations: WorldChoice[];
  reveals: WorldChoice[];
  treaty_minutes: number[];
  defaults: WorldOptions;
}

export interface WorldChoice {
  id: string;
  name: string;
  description: string;
}

export interface WorldOptions {
  type?: string;
  biome?: string;
  size?: string;
  resources?: string;
  separation?: string;
  reveal?: string;
  treaty_minutes?: number;
}

export interface WorldSize {
  id: string;
  name: string;
  description: string;
  tiles: number;
}

