import { readFile } from 'node:fs/promises';
import { test, expect, battlefieldKey, projectOpening } from './fixtures';

test('saves a named point, downloads SQLite and starts a separate game at the saved time',async({page,game},info)=>{
  await game.start('sandbox','peaceful',1,'Snapshot campaign');
  await game.command('pause',()=>page.getByRole('button',{name:'Pause match',exact:true}).click());
  const before=await game.snapshot();
  await page.getByRole('button',{name:'Match menu',exact:true}).click();
  await page.getByRole('button',{name:'Snapshots & exports',exact:true}).click();
  await expect(page.locator('#snapshot-list')).toContainText('No snapshots yet');
  await page.getByLabel('Snapshot name',{exact:true}).fill('Before expanding');
  const response=page.waitForResponse(r=>r.url().endsWith('/snapshots')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Save snapshot',exact:true}).click();
  expect((await response).ok()).toBe(true);
  await expect(page.locator('#snapshot-list')).toContainText('Before expanding');
  const fileEvent=page.waitForEvent('download');
  await page.locator('#snapshots-dialog').getByRole('button',{name:'Download SQLite file',exact:true}).click();
  const file=await fileEvent;expect(file.suggestedFilename()).toMatch(/\.sqlite$/);
  const bytes=await readFile((await file.path())!);expect(bytes.subarray(0,16).toString()).toBe('SQLite format 3\0');
  await page.screenshot({path:info.outputPath('named-snapshots-desktop.png')});
  await page.getByRole('button',{name:'Close snapshots',exact:true}).click();
  await game.command('pause',()=>page.getByRole('button',{name:'Resume match',exact:true}).click());
  await battlefieldKey(page,'.');
  const worker=before.entities.find(e=>e.type==='villager'&&e.owner===before.player.id)!;
  const point=await projectOpening(page,before,{x:worker.position.x-3,y:worker.position.y+2});
  await game.command('move',()=>battlefieldKey(page,'q').then(()=>page.mouse.click(point.x,point.y)));
  await expect.poll(async()=>(await game.snapshot()).time).toBeGreaterThan(before.time+1);
  await page.getByRole('button',{name:'Match menu',exact:true}).click();
  await page.getByRole('button',{name:'Snapshots & exports',exact:true}).click();
  await page.getByRole('button',{name:'Choose snapshot',exact:true}).click();
  await page.getByLabel('New game name',{exact:true}).fill('A different expansion');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:info.outputPath('named-snapshots-mobile.png')});
  const forked=page.waitForResponse(r=>r.url().endsWith('/fork')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Start from snapshot',exact:true}).click();
  expect((await forked).ok()).toBe(true);
  await expect(page.locator('#snapshots-dialog')).not.toBeVisible();
  await expect(page.locator('#connection')).toBeHidden();
  const after=await game.snapshot();expect(after.paused).toBe(true);expect(after.time).toBe(before.time);expect(after.player.resources).toEqual(before.player.resources);
  expect(after.entities.find(e=>e.id===worker.id)?.position).toEqual(worker.position);
  await expect(page.getByRole('button',{name:'Resume battle',exact:true})).toBeVisible();
});
